### ISSUE TITLE
hardware design

### ISSUE THREAD

**Issue by Sennevds** [jesusvallejo/Harman-kardon-ir-extender-hack#2]
Hi,

Could you include schematics how to wire the 3.5mm cable to the arduino?

**Comment by jesusvallejo** [comment]
sure, ill upload later a pic

**Comment by jesusvallejo** [comment]
done, as this is pretty custom made for my requirements somethings can look a bit odd, so in case u have any question dont hesitate to ask :)

**Comment by Sennevds** [comment]
Super thanks. At this moment I'm using esphome and a simple ir sender circuit like this:
![image](https://user-images.githubusercontent.com/3531609/83351669-6540b880-a346-11ea-98c5-e0e59520aec5.png)
So If I just replace the ir sensor with a 3.5mm plug it should work I think.

**Comment by jesusvallejo** [comment]
i think that too as the way the harman was desingned to just pass through the codes via that cable as "they are"(encoding an such) when received (and sended first).Also even if you dont have that exact harman as long as it has  HE1000 support youll be able to do it.
